import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json(newsData);
}

const newsData = {
  title: "Example news data response",
  description: "This is an example news data response.",
  statusCode: 200,
  data: [
    {
      id: 1,
      uniqueId: "unique1",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "New Renewable Energy Bill Passed",
      category: "Politics",
      date: "2025-07-04",
      author: "Jane Doe",
      content: "The government has passed a new bill aimed at boosting investment in renewable energy.",
      description: "The new bill introduces financial incentives for renewable energy projects, aiming to reduce the nation's dependence on fossil fuels and promote sustainability.",
    },
    {
      id: 2,
      uniqueId: "unique2",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Tech Giant Releases New AI Tool",
      category: "Technology",
      date: "2025-07-03",
      author: "John Smith",
      content: "A leading tech company unveiled a powerful new AI productivity tool for businesses.",
      description: "The tool is designed to automate administrative tasks and enhance business efficiency through machine learning and real-time analytics.",
    },
    {
      id: 3,
      uniqueId: "unique3",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Stock Markets Hit Record Highs",
      category: "Finance",
      date: "2025-07-03",
      author: "Emily Johnson",
      content: "Global stock markets surged today amid positive economic data and investor optimism.",
      description: "Investors are responding positively to strong quarterly earnings and signs of economic recovery across several major markets.",
    },
    {
      id: 4,
      uniqueId: "unique4",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Heavy Rain Causes Flooding in Jakarta",
      category: "Weather",
      date: "2025-07-02",
      author: "Ahmad Pratama",
      content: "Torrential rain in Jakarta has caused widespread flooding, displacing hundreds of residents.",
      description: "Emergency services are working around the clock to rescue affected families and provide temporary shelter and supplies.",
    },
    {
      id: 5,
      uniqueId: "unique5",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Indonesia Wins Southeast Asia Football Championship",
      category: "Sports",
      date: "2025-07-01",
      author: "Lisa Kusuma",
      content: "The Indonesian national team celebrated a historic win at the regional championship.",
      description: "With a dramatic 2-1 victory in the finals, the team captured its first championship in over a decade, sparking celebrations nationwide.",
    },
    {
      id: 6,
      uniqueId: "unique6",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Breakthrough in Cancer Treatment Research",
      category: "Health",
      date: "2025-06-30",
      author: "Dr. Anya Lim",
      content: "Scientists report a promising breakthrough in targeted cancer therapy during trials.",
      description: "Researchers have developed a new treatment that selectively attacks cancer cells, potentially improving survival rates and reducing side effects.",
    },
    {
      id: 7,
      uniqueId: "unique7",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "New Film Breaks Box Office Records",
      category: "Entertainment",
      date: "2025-06-29",
      author: "Michael Tan",
      content: "The latest blockbuster film has grossed over $300 million worldwide in its first week.",
      description: "The action-packed movie has drawn massive crowds globally, thanks to a strong fan base, positive reviews, and effective marketing.",
    },
    {
      id: 8,
      uniqueId: "unique8",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Farmers Protest Over Rising Costs",
      category: "Economy",
      date: "2025-06-28",
      author: "Rina Wijaya",
      content: "Farmers across several regions have staged protests over increasing fertilizer and fuel prices.",
      description: "The protests are calling for government subsidies and policy reforms to help ease the burden of rising agricultural production costs.",
    },
    {
      id: 9,
      uniqueId: "unique9",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "NASA Announces New Moon Mission Timeline",
      category: "Science",
      date: "2025-06-27",
      author: "Alex Newton",
      content: "NASA has revealed its updated plans for sending astronauts back to the moon by 2027.",
      description: "The mission will focus on establishing a sustainable lunar presence and preparing for future Mars expeditions.",
    },
    {
      id: 10,
      uniqueId: "unique10",
      imagePath: "https://dummyimage.com/1920x1080",
      title: "Cybersecurity Warning for Online Shoppers",
      category: "Technology",
      date: "2025-06-26",
      author: "Sarah Kim",
      content: "Experts are warning online shoppers to be vigilant as cyberattacks become more sophisticated.",
      description: "Security analysts recommend using two-factor authentication, secure websites, and updated antivirus software while shopping online.",
    },
  ]
};
